/* DROPS */

DROP SEQUENCE EMPRESA_SEQ;

DROP SEQUENCE CLIENTE_SEQ;

DROP SEQUENCE SERVICO_SEQ;

DROP TABLE SERVICO;

DROP TABLE CLIENTE;

DROP TABLE EMPRESA;

/* CREATES */

CREATE SEQUENCE EMPRESA_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE CLIENTE_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE SEQUENCE SERVICO_SEQ
  MINVALUE 1
  MAXVALUE 9999999999
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;
  
CREATE TABLE EMPRESA
(
	ID               	INT          	NOT NULL PRIMARY KEY,
	NOME             	VARCHAR(90)  	NOT NULL,
	ENDERECO		 	VARCHAR(100) 	NOT NULL,
	CNPJ			 	DECIMAL(14)		NOT NULL,
	TELEFONE         	DECIMAL(11)		NOT NULL,
	ESPECIALIDADE     	VARCHAR(100)	NULL
);

CREATE TABLE CLIENTE
(
	ID					INT				NOT NULL PRIMARY KEY,
	NOME 				VARCHAR(70)		NOT NULL,
	DATA_NASCIMENTO		TIMESTAMP		NOT NULL,
	TELEFONE			DECIMAL(11)		NOT NULL,
	CPF					DECIMAL(11)		NOT NULL,
	ENDERECO 			VARCHAR(100)	NOT NULL
);

CREATE TABLE SERVICO
(
	ID 					INT				NOT NULL PRIMARY KEY,
	ID_EMPRESA			INT 			NOT NULL,
	ID_CLIENTE			INT				NOT NULL,
	DESCRICAO			VARCHAR(200)	NOT NULL,
	VALOR				DECIMAL(8,2)	NOT NULL,
	DATA_SERVICO		TIMESTAMP		NOT NULL,
	CONSTRAINT SERVICO_CLIENTE_FK 
                FOREIGN KEY (ID_CLIENTE) 
                REFERENCES CLIENTE(ID),
    CONSTRAINT SERVICO_EMPRESA_FK 
                FOREIGN KEY (ID_EMPRESA) 
                REFERENCES EMPRESA(ID)
);

/* TESTE DE QUERYS
 
--CREATE
INSERT INTO EMPRESA (ID, NOME, ENDERECO, CNPJ, TELEFONE, ESPECIALIDADE) VALUES (EMPRESA_SEQ.NEXTVAL, 'Mecanincs Corp', 'Rua dos Testes', 39151174000190, 33733333, 'Mecânicos');

--RECOVERY
SELECT ID, NOME, ENDERECO, CNPJ, TELEFONE, ESPECIALIDADE FROM EMPRESA WHERE ID = 1;

--UPDATE
UPDATE EMPRESA SET NOME = 'Luzis Munís', ENDERECO = 'Rua Testante 24', CNPJ = 15262114000187, TELEFONE = 38459625, ESPECIALIDADE = 'Energia Elétrica' WHERE ID = 1;

--SEARCH
SELECT ID, NOME, ENDERECO, CNPJ, TELEFONE, ESPECIALIDADE FROM EMPRESA;

--DELETE
DELETE FROM EMPRESA WHERE ID = 1;

*

  
  